### ISSUE TITLE
Panic while shrinking process heap in full sweep GC

### ISSUE THREAD

**Issue by hansihe** [lumen/lumen#275]
I have hit this several times, but I lost track of the exact reproduction steps in the leadup to the keynote. I will update this issue with more details once I hit it again.

```
panicked at 'unable to shrink heap memory for process: realloc failed!: Alloc at liblumen_alloc/src/erts/process/alloc/process_heap_alloc.rs:179:13', src/libcore/result.rs:1084:5

Stack:

__wbg_new_59cb74e423758ede@webpack:///../pkg/interpreter_in_browser.js?:382:17
__wbg_new_59cb74e423758ede@http://localhost:8080/bootstrap.js:59:84
console_error_panic_hook::hook::h7ba898e25d7b3fc9@http://localhost:8080/32692a15580d2bde085c.module.wasm:wasm-function[800]:0x312b32
core::ops::function::Fn::call::ha5fa3fd59953e62f@http://localhost:8080/32692a15580d2bde085c.module.wasm:wasm-function[2957]:0x374518
std::panicking::rust_panic_with_hook::h55c31ca09c2ef439@http://localhost:8080/32692a15580d2bde085c.module.wasm:wasm-function[1345]:0x34a231
std::panicking::continue_panic_fmt::h52f4a8acaa363027@http://localhost:8080/32692a15580d2bde085c.module.wasm:wasm-function[2018]:0x3692ac
rust_begin_unwind@http://localhost:8080/32692a15580d2bde085c.module.wasm:wasm-function[2949]:0x3744c4
core::panicking::panic_fmt::h8625048e6a9f2c0c@http://localhost:8080/32692a15580d2bde085c.module.wasm:wasm-function[2294]:0x36f777
core::result::unwrap_failed::h56beaff7fe3ab5d8@http://localhost:8080/32692a15580d2bde085c.module.wasm:wasm-function[1977]:0x367fb3
liblumen_alloc::erts::process::gc::young_heap::YoungHeap::shrink::h841273bb2ee87f4d@http://localhost:8080/32692a15580d2bde085c.module.wasm:wasm-function[635]:0x2f6865
liblumen_alloc::erts::process::gc::collector::GarbageCollector::full_sweep::h1b60660ea11580d6@http://localhost:8080/32692a15580d2bde085c.module.wasm:wasm-function[93]:0x20cb3e
liblumen_alloc::erts::process::heap::ProcessHeap::garbage_collect::h308a31d9f64b5768@http://localhost:8080/32692a15580d2bde085c.module.wasm:wasm-function[1197]:0x33edce
liblumen_eir_interpreter::exec::CallExecutor::run_erlang::hdba3360bcc1b9a45@http://localhost:8080/32692a15580d2bde085c.module.wasm:wasm-function[353]:0x2ac259
liblumen_eir_interpreter::exec::CallExecutor::call_block::ha870e9c56a6d8a6a@http://localhost:8080/32692a15580d2bde085c.module.wasm:wasm-function[786]:0x3109fa
liblumen_eir_interpreter::code::interpreter_closure_code::hcb000988cc341fd7@http://localhost:8080/32692a15580d2bde085c.module.wasm:wasm-function[449]:0x2cb7ac
liblumen_alloc::erts::process::ProcessControlBlock::run::h82eb884031ea5dd1@http://localhost:8080/32692a15580d2bde085c.module.wasm:wasm-function[754]:0x30b7e9
lumen_runtime::scheduler::Scheduler::run_once::h67d7270bc60d73ec@http://localhost:8080/32692a15580d2bde085c.module.wasm:wasm-function[328]:0x2a24aa
lumen_web::request_animation_frames::{{closure}}::h609a255abc229187@http://localhost:8080/32692a15580d2bde085c.module.wasm:wasm-function[1605]:0x359437
<dyn core::ops::function::FnMut<()>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h669bf17c197bd2fc@http://localhost:8080/32692a15580d2bde085c.module.wasm:wasm-function[2568]:0x372bba
__wbg_elem_binding0@webpack:///../pkg/interpreter_in_browser.js?:52:98
real@webpack:///../pkg/interpreter_in_browser.js?:675:20
```

**Comment by hansihe** [comment]
This is reliably reproducible with the `ping_pong_count_large` in `liblumen_eir_interpreter`.

**Comment by hansihe** [comment]
```
=================================================== FULL GC
thread 'tests::ping_pong_count_large' panicked at 'unable to shrink heap memory for process: realloc failed!: Alloc at liblumen_alloc/src/erts/process/alloc/process_heap_alloc.rs:179:13', src/libcore/result.rs:1084:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at src/libcore/result.rs:1084
  11: core::result::Result<T,E>::expect
             at /rustc/72b2abfd65ba024e12d7fe51852a309419f494d8/src/libcore/result.rs:879
  12: liblumen_alloc::erts::process::gc::young_heap::YoungHeap::shrink
             at liblumen_alloc/src/erts/process/gc/young_heap.rs:200
  13: liblumen_alloc::erts::process::gc::collector::GarbageCollector::shrink_young_heap
             at liblumen_alloc/src/erts/process/gc/collector.rs:491
  14: liblumen_alloc::erts::process::gc::collector::GarbageCollector::full_sweep
             at liblumen_alloc/src/erts/process/gc/collector.rs:256
  15: liblumen_alloc::erts::process::gc::collector::GarbageCollector::collect
             at /home/hansihe/proj/rust/lumen/liblumen_alloc/src/erts/process/gc/collector.rs:86
  16: liblumen_alloc::erts::process::heap::ProcessHeap::garbage_collect
             at /home/hansihe/proj/rust/lumen/liblumen_alloc/src/erts/process/heap.rs:65
  17: liblumen_eir_interpreter::exec::try_gc
             at liblumen_eir_interpreter/src/exec/mod.rs:125
  18: liblumen_eir_interpreter::exec::CallExecutor::run_erlang
             at liblumen_eir_interpreter/src/exec/mod.rs:347
  19: liblumen_eir_interpreter::exec::CallExecutor::call_block
             at liblumen_eir_interpreter/src/exec/mod.rs:256
  20: liblumen_eir_interpreter::code::interpreter_closure_code
             at liblumen_eir_interpreter/src/code.rs:146
  21: liblumen_alloc::erts::process::Process::run
             at liblumen_alloc/src/erts/process.rs:771
  22: lumen_runtime::scheduler::Scheduler::run_once
             at lumen_runtime/src/scheduler.rs:124
  23: lumen_runtime::scheduler::Scheduler::run_through
             at lumen_runtime/src/scheduler.rs:181
  24: liblumen_eir_interpreter::call_result::call_run_erlang
             at liblumen_eir_interpreter/src/call_result.rs:51
  25: liblumen_eir_interpreter::tests::ping_pong_count_large
             at liblumen_eir_interpreter/src/tests/mod.rs:289
  26: liblumen_eir_interpreter::tests::ping_pong_count_large::{{closure}}
             at liblumen_eir_interpreter/src/tests/mod.rs:258
  27: core::ops::function::FnOnce::call_once
             at /rustc/72b2abfd65ba024e12d7fe51852a309419f494d8/src/libcore/ops/function.rs:227
  28: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/72b2abfd65ba024e12d7fe51852a309419f494d8/src/liballoc/boxed.rs:922
  29: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  30: std::panicking::try
             at /rustc/72b2abfd65ba024e12d7fe51852a309419f494d8/src/libstd/panicking.rs:275
  31: std::panic::catch_unwind
             at /rustc/72b2abfd65ba024e12d7fe51852a309419f494d8/src/libstd/panic.rs:394
  32: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1413
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
