### ISSUE TITLE
Spawn Chain Example form input is broken

### ISSUE THREAD

**Issue by KronicDeth** [lumen/lumen#378]
# Reproduction Steps
1. Run spawn-chain example in browser
2. Enter a number in form
3. Click submit button

## Actual
4. Open console and see exception.  No table rows are added

```
spawn_chain.js:782 panicked at 'ok_n_input (Box(0x1e0068)) is not a tuple', examples/spawn-chain/src/elixir/chain/on_submit_1/label_2.rs:30:5

Stack:

Error
    at Module.__wbg_new_59cb74e423758ede (webpack:///../pkg/spawn_chain.js?:767:17)
    at __wbg_new_59cb74e423758ede (http://localhost:8080/bootstrap.js:194:102)
    at console_error_panic_hook::hook::hd6b7c170b4680207 (wasm-function[453]:0x72ee9)
    at core::ops::function::Fn::call::h2b259af4f0132cb0 (wasm-function[2203]:0xb665b)
    at std::panicking::rust_panic_with_hook::hf3fbdd3bdaeaff86 (wasm-function[866]:0x99cd7)
    at rust_begin_unwind (wasm-function[1287]:0xacde4)
    at std::panicking::begin_panic_fmt::hcda8b83c8aa08ee0 (wasm-function[1445]:0xb08e7)
    at spawn_chain::elixir::chain::on_submit_1::label_2::code::h4e985fcc8f7f61c1 (wasm-function[389]:0x6a199)
    at liblumen_alloc::erts::process::Process::call_code::h9466494ce3d539a9 (wasm-function[949]:0x9ee50)
    at lumen_web::html_form_element::element_2::code::hcba9c5e601e08b54 (wasm-function[122]:0x2784d)


__wbg_error_4bb6c2a97407129a @ spawn_chain.js:782
__wbg_error_4bb6c2a97407129a @ bootstrap.js:200
console_error_panic_hook::hook::hd6b7c170b4680207 @ wasm-007fc81e-453:1
core::ops::function::Fn::call::h2b259af4f0132cb0 @ wasm-007fc81e-2203:1
std::panicking::rust_panic_with_hook::hf3fbdd3bdaeaff86 @ wasm-007fc81e-866:1
rust_begin_unwind @ wasm-007fc81e-1287:1
std::panicking::begin_panic_fmt::hcda8b83c8aa08ee0 @ wasm-007fc81e-1445:1
spawn_chain::elixir::chain::on_submit_1::label_2::code::h4e985fcc8f7f61c1 @ wasm-007fc81e-389:1
liblumen_alloc::erts::process::Process::call_code::h9466494ce3d539a9 @ wasm-007fc81e-949:1
lumen_web::html_form_element::element_2::code::hcba9c5e601e08b54 @ wasm-007fc81e-122:1
liblumen_alloc::erts::process::Process::call_code::h9466494ce3d539a9 @ wasm-007fc81e-949:1
spawn_chain::elixir::chain::on_submit_1::label_1::code::h2c143e3303a4e4c0 @ wasm-007fc81e-343:1
liblumen_alloc::erts::process::Process::call_code::h9466494ce3d539a9 @ wasm-007fc81e-949:1
lumen_web::event::target_1::code::h16e353c02a5a3798 @ wasm-007fc81e-88:1
liblumen_alloc::erts::process::Process::call_code::h9466494ce3d539a9 @ wasm-007fc81e-949:1
spawn_chain::elixir::chain::on_submit_1::code::hf7943a2b4f97a86b @ wasm-007fc81e-951:1
liblumen_alloc::erts::process::Process::call_code::h9466494ce3d539a9 @ wasm-007fc81e-949:1
lumen_runtime::otp::erlang::apply_3::code::hd31d6fc4ec6d8e97 @ wasm-007fc81e-114:1
liblumen_alloc::erts::process::Process::call_code::h9466494ce3d539a9 @ wasm-007fc81e-949:1
lumen_web::window::on_submit_1::code::h4996b8edbcd55ccc @ wasm-007fc81e-132:1
liblumen_alloc::erts::process::Process::run::h898c878cde4ceb31 @ wasm-007fc81e-232:1
lumen_runtime::scheduler::Scheduler::run_once::h85e4a9f1308c1b88 @ wasm-007fc81e-99:1
lumen_web::request_animation_frames::{{closure}}::hc107c176ba3e3680 @ wasm-007fc81e-1003:1
```

## Expected
4. Same output as calling `Chain.log_to_dom(n)` in console.

**Comment by KronicDeth** [comment]
After updating the `Debug` implementation for `arch_32` to match `arch_x86_64`, we get a better error:

```
spawn_chain.js:783 panicked at 'ok_n_input (Box(0x1e0068, literal = false, value=Term(Boxed<liblumen_alloc::erts::term::tuple::Tuple>(Tuple(Term(:'ok'), Box(0x1e0060, literal = false, value=Term(Boxed<liblumen_alloc::erts::term::resource::Resource>(Resource { header: Header<liblumen_alloc::erts::term::resource::Resource>(0b100111000), inner: 0x1d0048 => (type_id: TypeId { t: 8409696410853735648 }) Any } at 0x1e0060)))) at 0x1e0068)))) is not a tuple', examples/spawn-chain/src/elixir/chain/on_submit_1/label_2.rs:30:5

Stack:

Error
    at Module.__wbg_new_59cb74e423758ede (webpack:///../pkg/spawn_chain.js?:768:17)
    at __wbg_new_59cb74e423758ede (http://localhost:8080/bootstrap.js:194:102)
    at console_error_panic_hook::hook::hd6b7c170b4680207 (wasm-function[453]:0x72f41)
    at core::ops::function::Fn::call::h2b259af4f0132cb0 (wasm-function[2202]:0xb6616)
    at std::panicking::rust_panic_with_hook::hf3fbdd3bdaeaff86 (wasm-function[866]:0x99d2f)
    at rust_begin_unwind (wasm-function[1286]:0xacd9f)
    at std::panicking::begin_panic_fmt::hcda8b83c8aa08ee0 (wasm-function[1444]:0xb08a2)
    at spawn_chain::elixir::chain::on_submit_1::label_2::code::h4e985fcc8f7f61c1 (wasm-function[389]:0x6a1f1)
    at liblumen_alloc::erts::process::Process::call_code::h9466494ce3d539a9 (wasm-function[949]:0x9eea8)
    at lumen_web::html_form_element::element_2::code::hcba9c5e601e08b54 (wasm-function[122]:0x2784c)


__wbg_error_4bb6c2a97407129a @ spawn_chain.js:783
__wbg_error_4bb6c2a97407129a @ bootstrap.js:200
console_error_panic_hook::hook::hd6b7c170b4680207 @ wasm-007fc51e-453:1
core::ops::function::Fn::call::h2b259af4f0132cb0 @ wasm-007fc51e-2202:1
std::panicking::rust_panic_with_hook::hf3fbdd3bdaeaff86 @ wasm-007fc51e-866:1
rust_begin_unwind @ wasm-007fc51e-1286:1
std::panicking::begin_panic_fmt::hcda8b83c8aa08ee0 @ wasm-007fc51e-1444:1
spawn_chain::elixir::chain::on_submit_1::label_2::code::h4e985fcc8f7f61c1 @ wasm-007fc51e-389:1
liblumen_alloc::erts::process::Process::call_code::h9466494ce3d539a9 @ wasm-007fc51e-949:1
lumen_web::html_form_element::element_2::code::hcba9c5e601e08b54 @ wasm-007fc51e-122:1
liblumen_alloc::erts::process::Process::call_code::h9466494ce3d539a9 @ wasm-007fc51e-949:1
spawn_chain::elixir::chain::on_submit_1::label_1::code::h2c143e3303a4e4c0 @ wasm-007fc51e-343:1
liblumen_alloc::erts::process::Process::call_code::h9466494ce3d539a9 @ wasm-007fc51e-949:1
lumen_web::event::target_1::code::h16e353c02a5a3798 @ wasm-007fc51e-88:1
liblumen_alloc::erts::process::Process::call_code::h9466494ce3d539a9 @ wasm-007fc51e-949:1
spawn_chain::elixir::chain::on_submit_1::code::hf7943a2b4f97a86b @ wasm-007fc51e-951:1
liblumen_alloc::erts::process::Process::call_code::h9466494ce3d539a9 @ wasm-007fc51e-949:1
lumen_runtime::otp::erlang::apply_3::code::hd31d6fc4ec6d8e97 @ wasm-007fc51e-114:1
liblumen_alloc::erts::process::Process::call_code::h9466494ce3d539a9 @ wasm-007fc51e-949:1
lumen_web::window::on_submit_1::code::h4996b8edbcd55ccc @ wasm-007fc51e-132:1
liblumen_alloc::erts::process::Process::run::h898c878cde4ceb31 @ wasm-007fc51e-232:1
lumen_runtime::scheduler::Scheduler::run_once::h85e4a9f1308c1b88 @ wasm-007fc51e-99:1
lumen_web::request_animation_frames::{{closure}}::hc107c176ba3e3680 @ wasm-007fc51e-1003:1
```

This shows the box contains a tuple, so it doesn't make sense the `is_tuple` is returning false.

I'm investigating now if the `is_tuple` check isn't correct on `arch_32`, which would seem unlikely, but 🤷‍♂ .
