### ISSUE TITLE
Spawn Chain demo form with n >= 10 panics

### ISSUE THREAD

**Issue by KronicDeth** [lumen/lumen#380]
After applying #379 to fix #378, I tried increasing `n`.  1-9 work, but input 10 gets this error.

```
spawn_chain.js:782 panicked at 'ok_tbody (Box(0x200018, literal = false, value=Term(Boxed<liblumen_alloc::erts::term::resource::Resource>(Resource { header: Header<liblumen_alloc::erts::term::resource::Resource>(0b100111000), inner: 0x1d0af8 => (type_id: TypeId { t: 8409696410853735648 }) Any } at 0x200018)))) is not a tuple', examples/spawn-chain/src/elixir/chain/dom_output_1/label_12.rs:34:5

Stack:

Error
    at Module.__wbg_new_59cb74e423758ede (webpack:///../pkg/spawn_chain.js?:767:17)
    at __wbg_new_59cb74e423758ede (http://localhost:8080/bootstrap.js:194:102)
    at console_error_panic_hook::hook::hd6b7c170b4680207 (wasm-function[453]:0x72c57)
    at core::ops::function::Fn::call::h2b259af4f0132cb0 (wasm-function[2202]:0xb619d)
    at std::panicking::rust_panic_with_hook::hf3fbdd3bdaeaff86 (wasm-function[865]:0x998eb)
    at rust_begin_unwind (wasm-function[1284]:0xac881)
    at std::panicking::begin_panic_fmt::hcda8b83c8aa08ee0 (wasm-function[1443]:0xb03dd)
    at spawn_chain::elixir::chain::dom_output_1::label_12::code::hde88e48668a0c86a (wasm-function[345]:0x62d3c)
    at liblumen_alloc::erts::process::Process::run::h898c878cde4ceb31 (wasm-function[231]:0x4a484)
    at lumen_runtime::scheduler::Scheduler::run_once::h85e4a9f1308c1b88 (wasm-function[99]:0x1c9ad)


__wbg_error_4bb6c2a97407129a @ spawn_chain.js:782
__wbg_error_4bb6c2a97407129a @ bootstrap.js:200
console_error_panic_hook::hook::hd6b7c170b4680207 @ wasm-007f9f56-453:1
core::ops::function::Fn::call::h2b259af4f0132cb0 @ wasm-007f9f56-2202:1
std::panicking::rust_panic_with_hook::hf3fbdd3bdaeaff86 @ wasm-007f9f56-865:1
rust_begin_unwind @ wasm-007f9f56-1284:1
std::panicking::begin_panic_fmt::hcda8b83c8aa08ee0 @ wasm-007f9f56-1443:1
spawn_chain::elixir::chain::dom_output_1::label_12::code::hde88e48668a0c86a @ wasm-007f9f56-345:1
liblumen_alloc::erts::process::Process::run::h898c878cde4ceb31 @ wasm-007f9f56-231:1
lumen_runtime::scheduler::Scheduler::run_once::h85e4a9f1308c1b88 @ wasm-007f9f56-99:1
lumen_web::request_animation_frames::{{closure}}::hc107c176ba3e3680 @ wasm-007f9f56-1001:1
```

Visually, this results in the table missing the timing information.

![Screen Shot 2020-01-10 at 9 16 02 AM](https://user-images.githubusercontent.com/298259/72163722-f5776480-3389-11ea-845b-158b0fe4e859.png)

## Expected

With n=9, the time is shown as the last row

![Screen Shot 2020-01-10 at 9 15 00 AM](https://user-images.githubusercontent.com/298259/72163757-0627da80-338a-11ea-95b4-ceb412dc38b8.png)

**Comment by KronicDeth** [comment]
Applying this patch

```patch
diff --git a/lumen_web/src/document/get_element_by_id_2.rs b/lumen_web/src/document/get_element_by_id_2.rs
index 29e95736..b8a243be 100644
--- a/lumen_web/src/document/get_element_by_id_2.rs
+++ b/lumen_web/src/document/get_element_by_id_2.rs
@@ -22,5 +22,5 @@ pub fn native(process: &Process, document: Term, id: Term) -> exception::Result<
     let id_string: String = binary_to_string(id)?;
 
     option_to_ok_tuple_or_error(process, document_document.get_element_by_id(&id_string))
-        .map_err(|error| error.into())
+        .map_err(|error| panic!("{:?}", error))
 }
```

I found that the process is running out of memory and GC is triggered

```
Chain.log_to_dom(10)
```

```
spawn_chain.js:782 panicked at 'Alloc { backtrace: disabled backtrace }', lumen_web/src/document/get_element_by_id_2.rs:25:26

Stack:

Error
    at Module.__wbg_new_59cb74e423758ede (webpack:///../pkg/spawn_chain.js?:767:17)
    at __wbg_new_59cb74e423758ede (http://localhost:8080/bootstrap.js:194:102)
    at console_error_panic_hook::hook::hd6b7c170b4680207 (wasm-function[453]:0x72c57)
    at core::ops::function::Fn::call::h2b259af4f0132cb0 (wasm-function[2202]:0xb619d)
    at std::panicking::rust_panic_with_hook::hf3fbdd3bdaeaff86 (wasm-function[865]:0x998eb)
    at rust_begin_unwind (wasm-function[1284]:0xac881)
    at std::panicking::begin_panic_fmt::hcda8b83c8aa08ee0 (wasm-function[1443]:0xb03dd)
    at lumen_web::document::get_element_by_id_2::native::{{closure}}::hbbe57e5d70ac3a13 (wasm-function[1405]:0xaf793)
    at lumen_web::document::get_element_by_id_2::native::h2fae73152570b36e (wasm-function[736]:0x8f96c)
    at lumen_web::document::get_element_by_id_2::code::h7bc9e46db6a25ad4 (wasm-function[646]:0x87e02)
```

Which means this is a problem with re-entrancy probably.
