### ISSUE TITLE
Handle dynamic function calls in codegen

### ISSUE THREAD

**Issue by hansihe** [lumen/lumen#539]
Attempting to call a value results in a panic right now.

```erlang
-module(call).
-export([woo/1]).

woo({A}) -> A().
```

```
thread '<unnamed>' panicked at 'expected primop value', compiler/codegen/src/builder/function.rs:494:9
stack backtrace:
[snip]
  14: core::option::Option<T>::expect
             at /rustc/769d12eec1d0bc3708841dfc149d3ec98b04bec6/src/libcore/option.rs:349
  15: liblumen_codegen::builder::function::ScopedFunctionBuilder::get_primop
             at compiler/codegen/src/builder/function.rs:494
  16: liblumen_codegen::builder::ops::Callee::new
             at compiler/codegen/src/builder/ops.rs:161
  17: liblumen_codegen::builder::function::ScopedFunctionBuilder::build_block
             at compiler/codegen/src/builder/function.rs:918
  18: liblumen_codegen::builder::function::ScopedFunctionBuilder::build
             at compiler/codegen/src/builder/function.rs:661
  19: liblumen_codegen::builder::function::FunctionBuilder::build::{{closure}}
             at compiler/codegen/src/builder/function.rs:74
[snip]
```

**Comment by bitwalker** [comment]
Fixed with #554
